### ISSUE TITLE
"response appropriateness" score field in annotated dataset

### ISSUE THREAD

**Issue by ddehun** [ZHAOTING/dialog-processing#2]
Hi!

I read your paper (Designing Precise and Robust Dialogue Response Evaluators, ACL2020) and I downloaded your dataset to see the details.

It seems that your annotated DailyDialog dataset contains 4 Likert scale fields (content, grammar, overall, relevance). Among them, which one corresponds to the "response appropriateness" score, which is mainly used for the experiment on the paper? May I use the "overall" score as the "response appropriateness" to reproduce the results or study the future work?

Thanks!

**Comment by ddehun** [comment]
Also, How did you aggregate the annotated score, for instance, major voting or average the annotated score? Thanks!

**Comment by ZHAOTING** [comment]
Hi @ddehun , the "response appropriateness" score corresponds to the "overall" score in the annotations. Besides, footnote 2 in the paper has mentioned some results on "grammar" and "relevance". Since the "content" annotations have a low inter-annotator agreement score, we did not consider investigating it.
To aggregate the annotations, we simply use their average (excluding outliers).

**Comment by ddehun** [comment]
Hi, @ZHAOTING ! Thanks for your comment, and I have a new question about the paper. Sorry to bother you.

I tried to reproduce the performance of BLEU-2 in table 3 in your paper, but I failed. It seems that the Pearson and Spearman correlation should be about 0.31 and 0.23, but I got only about 0.08 and 0.05.

I used all of the samples in the dataset for this evaluation(not to 0.8:0.1:0.1), and each generated output is compared with the corresponding ground-truth sentence, that share the same context, to calculate the BLEU-2 score. 

Is there any critical fault in my evaluation, or it is just due to the split of the dataset? In the latter case, which split should I use to get similar performance with paper?

Thanks!

**Comment by ddehun** [comment]
Hi, @ZHAOTING ! Thanks for your comment, and I have a new question about the paper. Sorry to bother you.

I tried to reproduce the performance of BLEU-2 in table 3 in your paper, but I failed. It seems that the Pearson and Spearman correlation should be about 0.31 and 0.23, but I got only about 0.08 and 0.05.

I used all of the samples in the dataset for this evaluation(not to 0.8:0.1:0.1), and each generated output is compared with the corresponding ground-truth sentence, that share the same context, to calculate the BLEU-2 score.

Is there any critical fault in my evaluation, or it is just due to the split of the dataset? In the latter case, which split should I use to get similar performance with paper?

Thanks!

**Comment by ZHAOTING** [comment]
@ddehun No worry. Feel free to ask anytime.

The reported correlations are computed on the test split. However, the correlations of BLEU-2 are even a bit higher on the entire 720-response set (0.36 and 0.24).

I have used code from `src/utils/metrics.py (L230-261)` to compute BLEU. Maybe you want to share your implementation on the metric computation.

**Comment by ddehun** [comment]
Hi, @ZHAOTING !
I made a simple colab code to show my implementation after refer to your implementation in `metrics.py`.  This is from downloading the annotated dataset to calculate the correlation.

https://colab.research.google.com/drive/1Fh9Cv_4ERM0cz03b8vKfKibeIVfE0Qqr?usp=sharing

I use a Whitespace tokenizer (e.g., `sentence.split(' ')`) and 
compare the 'ground-truth' and others to calculate the BLEU2 score. I use every dataset to get the correlation score.
If you have time, please check my code and find any mistakes.

Thanks!

**Comment by ZHAOTING** [comment]
@ddehun I got it. I included "ground-truth"s in the response pool. If I exclude them, the correlation scores of BLEU will drop drastically (0.06 and 0.09).
The numbers are still different from yours, and I guess it is because that I used the average of *non-outlier* annotations as human score when I calculate the correlations.

**Comment by ddehun** [comment]
Hi, @ZHAOTING!
Thanks for your comment. After I included the 'ground-truth' into the response pool, I got the following correlation.
Pearson: 0.3776337241012718
Spearman: 0.24260213807617387
Now the correlation looks similar to your paper, and the minor difference in implementation(e.g., set split and outlier detection) seems the reason of the difference score. Thanks for your kindness.
