### ISSUE TITLE
Unable to load pre-trained model weights in the evaluation script.

### ISSUE THREAD

**Issue by aniket03** [ZHAOTING/dialog-processing#3]
Hi @ZHAOTING 

Thank you for making the code and data for the paper `Designing Precise and Robust Dialogue Response Evaluators` public.

I was trying to load pre-trained model weights (made available [here](https://zenodo.org/record/3828286#.X1_ly9YnafU) ) into the evaluation script (shared [here](https://github.com/ZHAOTING/dialog-processing/blob/master/src/tasks/response_eval/eval.py)), but torch.load with the model_file_path results in the error:`_pickle.UnpicklingError: invalid load key, 'f'`, with the following trace:

```
Traceback (most recent call last):
  File "/Users/aniket/miniconda3/envs/roberta-eval/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/aniket/miniconda3/envs/roberta-eval/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/aniket/dialog-processing/src/tasks/response_eval/eval.py", line 139, in <module>
    model.load_model(config.model_path)
  File "/Users/aniket/dialog-processing/src/model/response_eval/roberta.py", line 160, in load_model
    map_location=lambda storage, loc: storage
  File "/Users/aniket/miniconda3/envs/roberta-eval/lib/python3.7/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/aniket/miniconda3/envs/roberta-eval/lib/python3.7/site-packages/torch/serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'f'.
```

I tried a bunch of things here:
- Directly passed the `.pth.gz` file in the `torch.load()` method call, which yields same error.
- Tried `gzip -d roberta_eval.model.pt.gz` to un-compress the file but that results in error `gzip: roberta_eval.model.pt.gz: not in gzip format`.

Can you share what pre-processing needs to be done to the shared weights file so that it can be passed to the evaluation script. Would be super helpful.

**Comment by ZHAOTING** [comment]
Hi @aniket03, thanks for the info! 

I am experiencing the same problem on my laptop. The machine where I saved the model weights file is not accessible for the moment. Please wait for some time until I can access the machine and check the problem.

**Comment by ZHAOTING** [comment]
Hi @aniket03, I guess Zenodo corrupted the file when I uploaded it via command line. 
I have uploaded to [Zenodo](https://zenodo.org/record/4035820#.X2RttpMzblw) a new uncompressed weight file (size: 1.4GB) that works on my laptop, please check it out.

If there is no further problem, please feel free to close this issue. Thanks!

**Comment by aniket03** [comment]
Hi @ZHAOTING Thank you for helping with this issue. Will close this now.
