### ISSUE TITLE
DailyDialogue Utterance mapping to original dataset

### ISSUE THREAD

**Issue by johndmendonca** [ZHAOTING/dialog-processing#7]
Hi,

I was wondering if you have a mapping from the .json annotations to the original dataset. There seems to be an "id" at the start of each entry which at first I assumed was perhaps the entry/line in dailydialogue/dialogues_text.txt file but this doesn't seem to match:

`{"2521": {"context": [["B", "well , how does it look ?"], ["A", "it 's a perfect fit ."], ["B", "let me pay for it now ."]], "reference": ["A", "cash , credit ...`

actually corresponds to line 3519.

I was looking to do something with emotion as well, which is why I'm asking for this.

Cheers!

**Comment by ZHAOTING** [comment]
Hi @johndmendonca, the annotated sessions were randomly sampled from the original data and I didn't keep a record of their positions. So, I am afraid you could only find the corresponding session/utterance using some sort of (fuzzy) string matching or n-gram overlapping.

Sorry that I cannot help.

**Comment by johndmendonca** [comment]
Thanks anyways!
